# Generated by Django 5.1.2 on 2024-11-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0002_lesson"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ("pk",),
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ("pk",),
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
        migrations.AlterField(
            model_name="lesson",
            name="link_video",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на видео",
                max_length=150,
                null=True,
                verbose_name="Ссылка на видео",
            ),
        ),
    ]
